In [1]:
from google.colab import drive
drive.mount("/content/drive/")

Mounted at /content/drive/

In [2]:
import pandas as pd

In [3]:
Data= pd.read_csv("/content/drive/My Drive/DataBank/Bio.csv")

In [4]:
Data.head()

   Gender  FSIQ  VIQ  PIQ  Weight  Height  Salary
0    Male    50  120  115     102    64.5     250
1  Female    60  130  130     112    85.2     650
2  Female    70  140  145     122   105.9    1050
3  Female    80  150  160     132   126.6    1450
4    Male    90  160  175     142   147.3    1850